@rootUrl = http://localhost:5096

GET {{rootUrl}}/weatherforecast/
Accept: application/json

###
GET {{rootUrl}}/api/books
Accept: application/json 

###
GET {{rootUrl}}/api/books/3
Accept: application/json

###
# note sure here, added that enum as a string "BNEW"
# dunno if its parsed properly as an enum
# aight sent this multiple times 'di sya map lol 
# ASSJAKJS apparently when i connected this to the DB 
# naka autoincrement na si ID loollllllll
# DONT PUT HASHTAG INBETWEEN 

POST {{rootUrl}}/api/books
Content-Type: application/json
{
  "title": "Find MEEE",
  "author": "Andret Aciman",
  "purchase": "BNEW"
}

###
# walang kwenta yung id update here, should remove it
# liability pa if the id is updated, conflict 
PUT {{rootUrl}}/api/books/1
Content-Type: application/json
{
  "title": "Le Grand Meaulnes",
  "author": "Alain Henri",
  "purchase": "PSHOP"
}

###
DELETE {{rootUrl}}/api/books/1
Accept: application/json

# !IMPORTANT REFRESH/REBUILD WHENEVR U MAKE NEW REQUESTS
