// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StepOne.Data;

#nullable disable

namespace StepOne.Migrations
{
    [DbContext(typeof(BookAPIContext))]
    partial class BookAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StepOne.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Purchase")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Alain Henri",
                            Purchase = 2,
                            Title = "Le Grand Meaulnus"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Trevanian",
                            Purchase = 3,
                            Title = "The Summer of Katya"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George R.R. Martin",
                            Purchase = 1,
                            Title = "A Song of Ice and Fire: A Game of Thrones"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Terry Deary",
                            Purchase = 3,
                            Title = "Terrible Tudors"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
